version: '3.8'

services:
  net-guard-bot:
    build: .
    container_name: net-guard-bot
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./whitelist.json:/app/whitelist.json
    environment:
      - TELEGRAM_TOKEN=8683663523:AAFAY4TH8bAsugCAtwVTDeyr8osRGJm0V4E
      - CHAT_ID=6317626166s
      - NETWORK_INTERFACE=wlp3s0