version: '3.8'

services:
  net-guard-bot:
    build: .
    container_name: net-guard-bot
    restart: always
    network_mode: host
    volumes:
      - ./whitelist.json:/app/whitelist.json
    environment:
      - TELEGRAM_TOKEN=8T683663523:AAFAY4H8bAsugCAtwVTDeyr8osRGJm0V4E
      - CHAT_ID=6317626166s